### ISSUE TITLE
Plaatsen algemeen gevaarssymbool bij waterongevallen

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#101]
Als je het symbool algemeen gevaar wilt toevoegen bij waterongevallen komt er een vraagteken in beeld

**Comment by vnogzwarta** [comment]
betreft versie 3.3.0

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/109366230-2880fe00-7893-11eb-8423-e978ec646d0d.png)
 Wat mij betreft invalid
