### ISSUE TITLE
Dubbele invoervelden bij aanmaken terrein/object

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#102]
Bij het aanmaken van een nieuw terrein of gebied komt het soms voor dat na 1 klik er tweemaal een prompt invoerveld verschijnt waarin de naam moet worden opgegeven van het nieuw te maken object. Dit komt niet altijd voor, als dit echter wel het geval is verschijnt ook de OIV Objecten panel in QGIS tweemaal:

![a1](https://user-images.githubusercontent.com/73171956/109158785-21170300-7774-11eb-832c-8d716b06bd0c.jpg)
![a2](https://user-images.githubusercontent.com/73171956/109158789-21af9980-7774-11eb-93b8-9d82590d0cf9.jpg)

**Comment by ghost** [comment]
Betreft de laatste release van 3.3.0 die op dit moment beschikbaar is.

**Comment by Oostjoost** [comment]
Lag aan het niet juist afhandelen van de "Cancel" button
