### ISSUE TITLE
Tekenen dieptelijnen niet mogelijk

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#103]
In de laatst beschikbare release van 3.3.0 lopen collega's tegen het probleem aan dat dieptelijnen niet getekend kunnen worden binnen een terrein. Zowel open lijnen als gesloten lijnen geven hierbij problemen en worden niet opgeslagen. In de huidige productie-versie (3.1.0) werkt dit volgens dezelfde werkwijze wel.
![b2](https://user-images.githubusercontent.com/73171956/109159234-b0241b00-7774-11eb-94c3-86cb6ad49264.jpg)
![b4](https://user-images.githubusercontent.com/73171956/109159236-b0241b00-7774-11eb-8f03-d99f3ea49d4b.jpg)
![b5](https://user-images.githubusercontent.com/73171956/109159237-b0bcb180-7774-11eb-8bd4-491b6e9b7afb.jpg)
![b6](https://user-images.githubusercontent.com/73171956/109159238-b0bcb180-7774-11eb-9ddd-c76afbde8606.jpg)
![b7](https://user-images.githubusercontent.com/73171956/109159240-b0bcb180-7774-11eb-9efe-f21a4773474f.jpg)

**Comment by Oostjoost** [comment]
Om de één of andere reden heeft QGis er een LineString polygoon van gemaakt ipv de  MultiLineString. Geen idee hoe dit is gebeurd, aangezien er niets aan veranderd is. Na opnieuw toevoegen van de laag en relatie was het opgelost.
