### ISSUE TITLE
Bluswater datamodel synchroniseren met datamodel geo4oov

### ISSUE THREAD

**Issue by MartijnKuijpers** [OIV-NL-QGIS/QGIS_project#104]
Aangemaakt i.o.m. Joost. Aangezien alle waterleidingbedrijven de brandkranen aanleveren aan Geo4OOV en dat voor ons de bron is van de brandkranen zou het wenselijk zijn dat het datamodel van brandkranen overeenkomt met het datamodel van Geo4OOV registratie.

**Comment by Joachim-Tempelaars** [comment]
in v3.4.0 mee nemen

**Comment by OIV-NL-QGIS** [comment]
@MartijnKuijpers MartijnKuijpers  kan jij hier in voor zien kwa uren Joost?

**Comment by MartijnKuijpers** [comment]
MartijnKuijpers kan jij hier in voor zien kwa uren Joost?
Hoe wordt deze vraag bedoeld?

**Comment by Oostjoost** [comment]
Dit is hetzelfde als #172, is dus een wens die al langer speelt.
