### ISSUE TITLE
Aantal icons niet zichtbaar

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#107]
Als je bij repressief object onder tab "evenementen" symbool wilt toevoegen komt er een vraagteken in beeld.
o.a. bij gevaar elektrische spanning, lage temperatuur en algemeen gevaar

**Comment by vnogzwarta** [comment]
versie 3.3.0

**Comment by vnogzwarta** [comment]
blijkt ook bij tab "gevaren" bij tekenen in bouwlaag zo te zijn

**Comment by ghost** [comment]
Een aantal iconen kan ik reproduceren, zoals bv. bij tabblad gevaren: 'elektrische_spanning'. Het label dat dan verschijnt bevat de spelling met K, terwijl in het bestandssysteem wel een SVG aanwezig is met bestandsnaam 'electrische_spanning':
https://github.com/OIV-NL-QGIS/OIV_project/search?q=elektrische_spanning
https://github.com/OIV-NL-QGIS/OIV_project/search?q=electrische_spanning

Andere icons die geen andere naamgeving hebben werken wel, maar het bovenstaande voorbeeld niet:
![icons](https://user-images.githubusercontent.com/73171956/109502248-0953bd80-7a99-11eb-94df-0b4e84c48f55.png)

**Comment by ghost** [comment]
![icon2](https://user-images.githubusercontent.com/73171956/109502706-a151a700-7a99-11eb-8d63-e92785b46889.png)
![icon1](https://user-images.githubusercontent.com/73171956/109502710-a1ea3d80-7a99-11eb-94a2-9c9db90ce1fd.png)

**Comment by Oostjoost** [comment]
Ik heb alle symbolen nagelopen, zowel bij bouwlaag als repressief object en kwam bij de volgende symbolen spelfouten tegen, hetzij in de naam van de SVG of in de symbol_name in de database:

**Veiligheidsvoorzieningen ruimtelijk**
- afsluiter_noodschakelaar -> SVG heette Noodstop
- reduceer_drukbegrenzer -> symbo_name in database was reduceer_drukbegerenzer

**Dreiging**
- elektrische spanning - > SVG met een k
- lage temperatuur of bevriezing -> SVG '_of_bevriezing' mistte

**Industrie**
- brandbestrijdings_materiaal -> SVG geen underscore
- calamiteiten_coördinatiecentrum -> SVG geen ümlaut

Deze heb ik aangepast.

**Comment by Oostjoost** [comment]
Complimenten dat er door jullie zo goed getest wordt!!!
