### ISSUE TITLE
Legenda functioneert deels niet meer

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#108]
In versie 3.3.0 zit een issue m.b.t. de legenda. In de huidige productie-omgeving (3.0.9) wordt dit als volgt getoond:
![legenda-1](https://user-images.githubusercontent.com/73171956/109486484-3c8b5200-7a83-11eb-95a3-60d05e3fa567.png)

In de huidige test-omgeving (versie 3.3.0, commit 5c936ed38a6b2f4fb3a6ce0be3771cb00972c3b9, daarvan is een nieuwe setup gecompiled) ziet dit er als volgt uit:
![legenda-2](https://user-images.githubusercontent.com/73171956/109486499-401ed900-7a83-11eb-8ed2-2082613c66f8.png)

**Comment by Oostjoost** [comment]
De symboolnaam en grootte komt "dynamisch" vanuit de database. Dus de symbol_name+.svg bepaalt het symbool van het punt-object. Omdat dit dynamisch wordt aangeroepen kan QGIS er geen legenda meer van maken. Gemaakt zoals ontworpen.
