### ISSUE TITLE
symbool "te water laat plaats" onduidelijk

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#109]
Onder de tab Waterongevallen kun je een symbool plaatsen voor "te water laat plaats" dit symbool is heel erg wazig zou dit symbool vervangen kunnen worden door een betere?

**Comment by ghost** [comment]
Betreft plugin versie 3.3.0, QGIS 3.10, commit 5c936ed38a6b2f4fb3a6ce0be3771cb00972c3b9, daarvan is een nieuwe setup gecompiled.

**Comment by ghost** [comment]
![boat](https://user-images.githubusercontent.com/73171956/109497693-b840cb00-7a92-11eb-876a-646efdcb7e7c.png)

**Comment by ghost** [comment]
![boat2](https://user-images.githubusercontent.com/73171956/109497775-da3a4d80-7a92-11eb-8977-f3fb9f5eb74d.png)

Gebruikte schermresolutie: 1920x1080

**Comment by Joachim-Tempelaars** [comment]
in 3.3.2 mee nemen

**Comment by OIV-NL-QGIS** [comment]
Deze gaat mee naar de pictogrammen werkgroep

**Comment by vnogzwarta** [comment]
![slipway_icon_180124](https://user-images.githubusercontent.com/66950297/123395874-f792aa80-d5a0-11eb-96e9-28a967aeafbe.png)
