### ISSUE TITLE
"bijzondere ruimte" onder functie Objecten 3.3.0

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#110]
Als je een bijzondere ruimte tekent dan heeft deze geen gele vulling meer maar alleen de arcering, heeft dit een reden?
Met vulling is dit beter zichtbaar.....

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/110716462-856fa300-8207-11eb-894d-f27121aff915.png)
