### ISSUE TITLE
inkleuring aangemaakte objecten

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#111]
Misschien is het strak om de aangemaakte objecten dezelfde gele kleur te geven als de functie "ruimten", in een van de eerste versies van de plugin was dit wel het geval nu zijn de objecten meer beige.

**Comment by Oostjoost** [comment]
In deze versie en 3.2.0 ook al is het ingeregeld dat een regionaal beheerder de styling van vlakken, lijnen etc. bijna helemaal zelf kan bepalen via de database. Een volgende wens/uitbreiding gaat nog zijn dat dit geconfigureerd kan worden via QGIS.

![afbeelding](https://user-images.githubusercontent.com/23038880/109709253-916ebb80-7b9c-11eb-98d3-a4d66be4077b.png)
