### ISSUE TITLE
aanmaken nieuwe bouwlaag 3.3.0

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#112]
Als je een nieuwe bouwlaag aanmaakt en deze wilt overnemen van een andere bouwlaag heb je de optie om een aantal lagen mee te kopiëren. Als je vervolgens een aantal lagen selecteert wordt de bouwlaag wel aangemaakt maak de geselecteerde lagen niet.

**Comment by ghost** [comment]
Betreft release die is bijgewerkt tot en met versie d71c175bb85be6a48a31d2d8e1b243fc17a87d7a

**Comment by Joachim-Tempelaars** [comment]
in v3.3.1 mee nemen

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/OIV_project/commit/f5d0fb82c98c6c2094df44648aedde354d8e27b2
resolves #112
