### ISSUE TITLE
symbool algemeen gevaar

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#113]
In de nieuwe release staat het symbool algemeen gevaar er wel bij maar geeft vraagteken.
In de icons heeft symbool als omschrijving "algemeen_gevaar" en in de tabbladen van de plugin "algemeen_gevaar_1" of "algemeen_gevaar_2" kan dit de reden zijn van niet tonen?

**Comment by ghost** [comment]
Betreft release die is bijgewerkt tot en met versie d71c175bb85be6a48a31d2d8e1b243fc17a87d7a. Gaat mogelijk om hetzelfde issue als hier gemeld: https://github.com/OIV-NL-QGIS/OIV_project/issues/107

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/109884915-049c2e80-7c7e-11eb-9e31-0b670c0f561a.png)

werkt gewoon.... en heeft niets te maken met de tooltip van de button in de plugin.

**Comment by ghost** [comment]
In de map met icons staat: **C:\ProgramData\OIV-3.3.0\svg\algemeen_gevaar.svg**. Dan zie ik bij het plaatsen van het onderstaande icon het volgende resultaat:
![icon](https://user-images.githubusercontent.com/73171956/110327447-46c8c580-801a-11eb-8fbb-c962fcff2212.jpg)
![icon1](https://user-images.githubusercontent.com/73171956/110327549-65c75780-801a-11eb-8cad-69d4e85193cd.png)

Wanneer ik het bestand **C:\ProgramData\OIV-3.3.0\svg\algemeen_gevaar.svg** kopieer naar: **algemeen_gevaar_1.svg** en **algemeen_gevaar_2.svg** zie ik, zonder ook maar iets in QGIS te doen:
![icon2](https://user-images.githubusercontent.com/73171956/110327707-99a27d00-801a-11eb-8991-0b2aa953d3a7.png)

**Comment by Oostjoost** [comment]
Links de plugin configuratie, van button naar id waarde voor de database, en rechts de vertaling in de database van id naar een symbol_name.

![afbeelding](https://user-images.githubusercontent.com/23038880/110389007-32a9b600-8064-11eb-9135-d62b1e7eed44.png)

Dan klopt er misschien iets anders niet, maar de "button_name" welke de plugin gebruikt heeft niets te maken met de symbol_name aangezien die uit de database vandaan komt. In de de database wordt namelijk het "id" opgeslagen en het is is gekoppeld aan een symbol_name.

**Comment by ghost** [comment]
Dank voor de info. Enig idee waar dit probleem dan mogelijk door ontstaat @Oostjoost? Het enige dat ik aanpas is de bestandsnaam in het bestandssysteem, direct daarna is de icon zichtbaar. Zodra ik het gedupliceerde bestand op het bestandssysteem verwijder, is ook direct de icon in QGIS verdwenen. Verder pas ik nergens iets aan, puur in het bestandssysteem zelf.

**Comment by vnogzwarta** [comment]
Goedemorgen Joost en Carlo,

Wat we nog tegen zijn gekomen:

  *   Onder TAB blad bluswater symbool bluswater defect (rode kruis) geeft ook een vraagteken
  *   Onder Tab blad Algemeen bij Object terrein aanmaken symbool reduceer_drukbegrenzer geeft ook een vraagteken

**Comment by vnogzwarta** [comment]
Nog een nabrander 😊:


  *   Symbool sleutelkluis_hbr (blauwe sleutelkluis) onder tab industrie geeft ook een vraagteken.
Nu hebben we echt alle symbolen gehad……

**Comment by Oostjoost** [comment]
> 
> 
> Dank voor de info. Enig idee waar dit probleem dan mogelijk door ontstaat @Oostjoost? Het enige dat ik aanpas is de bestandsnaam in het bestandssysteem, direct daarna is de icon zichtbaar. Zodra ik het gedupliceerde bestand op het bestandssysteem verwijder, is ook direct de icon in QGIS verdwenen. Verder pas ik nergens iets aan, puur in het bestandssysteem zelf.

@vr-cb probleem is achterhaald. Bij jullie in de database staat vermoedelijk bij de symbol_name van algemeen_gevaar  in de tabel objecten.dreiging_type (id->129) algemeen_gevaar_2

Ik zorg eind deze week voor een bug-fix versie 3.3.1 waarin dit is verholpen via een db script. Zie ook de database GitHub:
https://github.com/OIV-NL-QGIS/OIV_database/blob/migratie_3.4/migratiescripts/migratie_3.3.0-3.3.1.sql

Dit lost direct ook het probleem met de reduceer op.

**Comment by Oostjoost** [comment]
Voor sleutelkluis_hbr idem als hierboven.

Dank jullie voor het goede testen van de symbolen!

**Comment by Joachim-Tempelaars** [comment]
in 3.3.1 mee nemen

**Comment by Oostjoost** [comment]
opgelost in met name de database, zie 
https://github.com/OIV-NL-QGIS/OIV_database/blob/migratie_3.4/migratiescripts/migratie_3.3.0-3.3.1.sql
