### ISSUE TITLE
De formulieren in oiv object blijven klein. Het betreft de volgende tabbladen: bedrijfshulpverlening, contactpersonen, scenario, en organisatorisch.  Dit is in de versie 3.2.4.

### ISSUE THREAD

**Issue by MartijnKuijpers** [OIV-NL-QGIS/QGIS_project#115]
**Beschrijf de bug - kort en duidelijk**

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...'
2. '...'
3. 

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 
 - QGis versie:
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Joachim-Tempelaars** [comment]
in 3.3.1 mee nemen
