### ISSUE TITLE
Bouwkundige veiligheidsvoorzieningen vallen buiten de bouwlaag waaraan ze gekoppeld zijn

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#116]
Binnen de VNOG zijn we druk bezig met de nieuwe release in de test-omgeving. Hier werken al een aantal collega's mee en delen hun bevindingen, dus dat is top. 
Nu zijn we ook bezig met de vertoning van alles in de plugin naar de MDT's op de voertuigen. Daar lopen we tegen een probleem aan dat al langer speelt, maar nu pas aan het licht komt. 

Van alle bouwkundige veiligheidsvoorzieningen in onze database is ongeveer 8% gekoppeld aan een andere bouwlaag. 
Hiervoor heb ik `objecten.bouwlagen` en `objecten.bouwlaag_veiligh_bouwk` gebruikt (welke gekoppeld is met `bouwlaag_id`). Met een disjoint heb ik gekeken naar de scheidingen die nu ingetekend zijn, maar dus volledig buiten de geometrie van de bouwlaag vallen waar je ze in ziet staan.

In de QGIS applicatie is dat niet eerder aan het licht gekomen, omdat je van alle objecten rondom alles ziet. Het komt nu naar voren nu we van 1 specifiek terrein alles willen tonen in de MDT. Dan blijkt dat scheidingen van een ander pand meegeselecteerd worden op basis van `bouwlaag_id`, terwijl deze dus volledig hierbuiten vallen.

Voor de duidelijkheid: dit heeft niets met de nieuwste release te maken, het probleem zien we ook in de huidige productie-omgeving waar nog versie 3.0.9 gebruikt wordt. Bij een aantal recent ingetekende objecten weten mijn collega's zeker dat ze in het juiste pand hebben gewerkt. Ze hebben namelijk alles tegelijkertijd gemaakt.

Ik ben benieuwd of andere regio's ook tegen dit probleem aan lopen/liepen? Hoor het graag, vast bedankt!

**Comment by Joachim-Tempelaars** [comment]
in v3.3.1 mee nemen

**Comment by ghost** [comment]
@Oostjoost: op basis hiervan kijk ik naar de bouwkundige veiligheidsvoorzieningen die buiten de administratief gekoppelde bouwlaag vallen:

```
select v.*
from objecten.bouwlagen bl
left join objecten.bouwlaag_veiligh_bouwk v on bl.id = v.bouwlaag_id
where ST_IsValid(v.geom) and ST_IsValid(bl.geom) and ST_Disjoint(v.geom, bl.geom);
```

**Comment by Oostjoost** [comment]
Dit zou 3 mogelijke oorzaken kunnen hebben welke eigenlijk alledrie niet hun oorsprong vinden in de plugin.
- Ergens in een conversie zouden verkeerde koppelingen kunnen zijn gelegd. De kans hierop was met name het grootst ten tijde van de implementatie van de bouwlagen in het datamodel. Voor het koppelen is vaak "nearest neighbour" toegepast.
- Het zou een "gebruikersfout" kunnen zijn. Als je op een bouwlaag tekent en je gaat ergens anders (bijvoorbeeld ander pand) verder met tekenen dan blijft de plugin koppelen aan de nog steeds geselecteerde bouwlaag. Hiervoor zouden we nog een extra controle kunnen toevoegen aan de plugin. Indien er geen intersect is met de bouwlaag waarop men aan het tekenen is zou er een waarschuwing kunnen worden afgegeven.
- Indien een bouwlaag gekoppeld aan een padn uit meerdere bouwdelen bestaat, koppelt de plugin aan de "nearest neighbour". Hierdoor zou theoretisch aan de verkeerde kunnen worden gekoppeld. zie onderstaande afbeelding. Als op de pijl iets getekend wordt dan weet de plugin alleen de bouwlaag, maar niet of het linker of rechter deel nu wordt bedoeld. Vandaar "nearest neighbour" om de juiste te selecteren. Je zou natuurlijk de gebruiker kunnen dwingen om een keuze te maken, maar dan wordt het haast niet meer werkbaar (is destijds besloten, kan nu wel anders zijn).

De mogelijkheid bestaat natuurlijk dat een gebruiker wel buiten het pand tekent.

![afbeelding](https://user-images.githubusercontent.com/23038880/110816258-792d2980-828b-11eb-9ff1-6f35d83597a2.png)

**Comment by Oostjoost** [comment]
Een oplossing zou zijn om een update query uit te voeren in de database om alle bouwkundige veiligheidsvoorzieningen te koppelen aan de dichtsbijzijnde bouwlaag. Uitdaging hierbij is wel de "bouwlaag", als dit natuurlijk op elkaar gestapelde vlakken zijn dan zijn ze allemaal de dichtsbijzijnde. In de view bouwlaag_veiligh_bouwk staat wel de bouwlaag (getal) waar de scheiding nu aan gekoppeld zit. Deze zou je kunnen hergebruiken voor deze exercitie.

Ik ben wel van mening dat dit geen bug is in de applicatie, maar dat het wel beter zou zijn om zowel bouwlaag als bouwdeel te selecteren voordat je gaat tekenen.

**Comment by vnogzwarta** [comment]
Uit een check blijkt dat dezelfde symbolen die meerdere keren zijn geplaatst in een bouwlaag soms wel aan de juiste bouwlaag gekoppeld zitten en soms ook weer niet.... picto kan dan zo maar gekoppeld worden aan de bouwlaag van het pand aan de overkant van de straat.

**Comment by vnogzwarta** [comment]
Bij de panden waar dit probleem zich voordoet hebben we soms ook problemen met het aanmaken van een extra bouwlaag dan komt er een foutmelding (zie hieronder)
![fout aanmaken bouwlaag 3 3 1 beta](https://user-images.githubusercontent.com/66950297/110909461-64df4000-8310-11eb-97ef-39dfb8bfe1bc.JPG)

**Comment by ghost** [comment]
Bovenstaande beschrijving betreft de nieuwe release `v3.3.1-beta1`, met de daarbij uitgevoerde database-migratie.

**Comment by vnogzwarta** [comment]
Na uitvoerig testen in zowel versie 3.0.9 als in versie 3.3.0 en 3.3.1 beta lijkt het probleem zich willekeurig voor te doen, misschien kunnen we via teams een keer wat laten zien om e.e.a te verduidelijken? Dus bij het helemaal opnieuw aanmaken van een Object en dan aanmaken van nieuwe bouwlaag in versie 3.3.1 beta ontstaat het probleem ook dat er picto's aan een andere bouwlaag worden gekoppeld.

**Comment by ghost** [comment]
@Oostjoost heb je een voorkeur voor een moment om af te stemmen via Teams? Dan kunnen we indien mogelijk wat inplannen waarbij mijn collega's e.e.a. tonen zoals hierboven beschreven.

**Comment by ghost** [comment]
We hebben alle historische records doorgelopen en gescand, en waar nodig aangepast. Nu is alles up-to-date en correct gekoppeld. Voor nu sluiten we het issue.

**Comment by ghost** [comment]
Dag @Oostjoost ,

Collega's lopen opnieuw tegen dit probleem aan. Alle historische records zijn een tijd terug goed gezet, en dat werkt. Maar bij nieuw getekende objecten speelt dit dus opnieuw. In welke richting kunnen we een oplossing zoeken?

**Comment by ghost** [comment]
Terugkoppeling van @vnogzwarta:

_We hebben dit zojuist even getest in de testomgeving met versie 3.3.4 en het probleem lijkt toch wel te komen o.a. door nearest neighbour…. Onze werkvolgorde is goed we doorlopen dezelfde stappen maar bij een bepaalde afstand gaat het zeker fout dit kunnen we aantonen.
Als er een symbool dichter bij een andere bouwlaag geplaatst wordt (terwijl deze bouwlaag niet is geselecteerd ) wordt het symbool wel aan deze andere niet geselecteerde bouwlaag gekoppeld…_

**Comment by ghost** [comment]
Joost gaat inventariseren hoeveel werk het is om deze nearest neighbour functie te beperkten tot het BAG pand waarop gewerkt wordt. Voor nu halen we deze tijdelijk uit de milestone. Indien tijd over, dan graag oppakken.

**Comment by Oostjoost** [comment]
Ik liep er nu zelf ook tegenaan voor Zuid-Limburg. Ik heb de voorgestelde oplossing gelijk geïmplementeerd en dit lijkt veel beter te gaan. Wel nog even goed testen.

**Comment by Oostjoost** [comment]
Zelf uitvoerig getest bij het tekenen en het lijkt nu goed te gaan.
