### ISSUE TITLE
Python fout bij aanklikken symbolen bouwlaag

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#117]
**Python fout bij symbolen bouwlaag**

Bij bouwlaag tekenen, klik op een willekeurig symbool en er komst een foutmelding
![image](https://user-images.githubusercontent.com/64782528/110504774-c8455400-80fd-11eb-9b40-8122a5f1c675.png)

**Comment by Oostjoost** [comment]
Onduidelijke melding, maar in ieder geval een foutafhandeling toegevoegd als de laag niet bestaat waaruit de features worden opgehaald. Dus in bovenstaande geval als lyr niet bestaat kunnen er ook geen features worden opgevraagd.

**Comment by Joachim-Tempelaars** [comment]
In v3.3.1 mee nemen
