### ISSUE TITLE
Geen unieke id in view_bouwlagen indien terreinen overlappen

### ISSUE THREAD

**Issue by MartijnKuijpers** [OIV-NL-QGIS/QGIS_project#119]
Indien terreinen overlappen dan wordt een bouwlaag meerdere keren opgenomen in de view_bouwlagen. Hierdoor is er geen unieke identifier meer.

Dit geldt ook voor alle andere views gekoppeld aan de bouwlagen.

**Comment by OIV-NL-QGIS** [comment]
Deze Bug gaat mee naar fix 3.3.2

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/OIV_database/blob/migratie_3.4/migratiescripts/migratie_3.3.1-3.3.2.sql
resolves #119
