### ISSUE TITLE
Aanpassen volgorde in filtering

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#12]
Volgorde filtering aanpassen. Eerst soort dan van tot

**Comment by Paulienv78** [comment]
Symbolen voor waterongeval, natuur, evenement

**Comment by Oostjoost** [comment]
Ik neem aan dat er ook een symbool voor gebouw moet komen en dat dan het i-tje eigenlijk verdwijnt

**Comment by Oostjoost** [comment]
Gereed, volgorde aangepast
