### ISSUE TITLE
Voertuig viewer View POI en gebied gerichte aanpak nog maken 

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#120]
**Beschrijf de bug - kort en duidelijk**

**Hoe te reproduceren**
Beschrijf de stappen hoe de bug te reproduceren is:
1. '...'
2. '...'
3. 

**Stapelspoor**
Maak waar mogelijk een screenshot van het stapelspoor

**Wat wordt er verwacht**
Beschrijf kort en duidelijk welk gedrag er wordt verwacht van de applicatie

**Screenshots**
Indien van toepassing voeg screenshots of een filmpje toe.

**Op welk device kwam de issue naar voren**
 - Besturingssysteem en versie: 
 - QGis versie:
 - Database connectie of WFS connectie:
 - Welke versie van Postgres/PostGis:
 - Welke versie van GeoServer:

**Wilt u verder nog wat opmerken**

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/OIV_database/blob/master/migratiescripts/migratie_3.3.1-3.3.2.sql
resolves #120
