### ISSUE TITLE
Ruimten tekenen in bouwlaag niet zichtbaar

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#124]
Als er ruimten getekend worden in de bouwlaag dan zijn deze niet zichtbaar.

In de attributentabel zijn ze wel zichtbaar.

Wanneer ik handmatig een ruimte wil tekenen via de laag dan krijg ik de volgende melding:

![image](https://user-images.githubusercontent.com/64782528/111997891-caef7280-8b1b-11eb-939a-bf385aa7482c.png)

**Comment by Oostjoost** [comment]
Vinkje voor stijl "Anders" staat uit. Even zelf aanzetten, Reeds in het project opgeslagen dat wordt meegenomen in 3.3.2

**Comment by Paulienv78** [comment]
Dank je wel. Dit was het euvel. De ruimten zijn nu zichtbaar in het project
