### ISSUE TITLE
Snappen in de lagen "ruimten" en "bouwkundige veiligheidsvoorzieningen" werkt niet optimaal

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#126]
Snappen in lagen bouwkundige veiligheidsvoorzieningen en ruimten werkt niet optimaal waardoor de lijnen niet netjes gekoppeld kunnen worden en niet goed aansluiten. Diverse "snapinstellingen" aangepast maar zonder resultaat heeft iemand hier een oplossing voor?

**Comment by Oostjoost** [comment]
Snappen maakt geen gebruik van de snap-instellingen van QGis.
Kan iemand toelichten, wat wordt bedoeld met niet optimaal? En zonder voorbeeld kan ik niets analyseren.

**Comment by vnogzwarta** [comment]
![image](https://user-images.githubusercontent.com/66950297/112477630-8100c980-8d73-11eb-9224-811c9fb7ab8e.png)
![image](https://user-images.githubusercontent.com/66950297/112477774-a1c91f00-8d73-11eb-8fd9-963d4494d89b.png)

**Comment by vnogzwarta** [comment]
De hulplijn wordt keurig gevolgd maar als dan vervolgens de lijn in beeld komt waar op aangesloten moet worden krijg je onnauwkeurige aansluitingen zie voorbeelden hierboven

**Comment by Oostjoost** [comment]
Het snappen werkt zoals destijds afgesproken. Bouwdeelkundige scheidingen, Ruimten, Bag Panden, maar ook hulplijnen zijn snapbaar. Dit is geprogammeerd in de tool. Dus ik zie het als een uitbreiding een geen bug.
Mogelijke oplossingen zijn prioritering aanbrengen in snapvolgorde of (en deze is veel moeilijker) kruispunten berekenen tussen verschillende kaartlagen. Dus een kruispunt berekenen van bijvoorbeeld een hulplijn met een scheiding.

Dus dit betreft in eerste instantie een functioneel vraagstuk.

**Comment by ghost** [comment]
Issue gesloten, intern besproken. Voor nu geen uitbreiding nodig van de functionaliteit.
