### ISSUE TITLE
DXF import loopt vast 

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#127]
DXF import loopt vast door ontbreken regel pyhon code  joost weet waar het zit.

**Comment by Oostjoost** [comment]
Hij loopt niet vast. Bij een ongeldige geometrie krijg je een pop-up. Bij een import moet deze pop-up niet verschijnen. Dus met één regel code kan ik die onderdrukken.
