### ISSUE TITLE
Window-size van OIV-objecten

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#129]
De venstergrootte van de plugin is soms langer in een regulier scherm past (1920x1080), terwijl er onderaan het scherm nog ruimte is. De knoppen onderaan vallen daardoor uit het zicht. Dit kwam een collega tegen tijdens het inspecteren van een bouwlaag:
![windowsize](https://user-images.githubusercontent.com/73171956/113265447-6f1fa900-92d4-11eb-9fd2-33443437de80.jpg)

QGIS: 3.16.5
Plugin: 3.3.2 / commit 73aa6b9ff0c4216d440ee9bf753aca53986c2e25

**Comment by ghost** [comment]
Reproduceren: als je met het blauwe I-icon iets wilt selecteren en op gereed klikt, dan verandert het formaat.

**Comment by Oostjoost** [comment]
Dit is al een vaker terugkerend issue. Vergt deels opnieuw maken (her-inrichten) van formulieren in de plugin. Eigenlijk moet elk formulier worden ingericht met een extra scroll-area op de tabbladen.

**Comment by Oostjoost** [comment]
i.o.m. August verschoven naar 3.3.7

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
dit moet even goed getest worden, maar ik denk dat het is opgelost
