### ISSUE TITLE
Het kunnen wijzigen van object contouren lukt niet meer in de laatste versie 3.3.2

### ISSUE THREAD

**Issue by MartijnKuijpers** [OIV-NL-QGIS/QGIS_project#130]

**Comment by Oostjoost** [comment]
Is dit wel zo?

**Comment by MartijnKuijpers** [comment]
Beste collega's,

Bij mij slaat het project vast als ik een mutatie wil doen aan de contouren.

Met vriendelijke groet,
***@***.***D76425.FD913B00]

M.P.M (Martijn) Kuijpers | medewerker operationele voorbereiding | Cluster Noord | Brandweer Midden- en West-Brabant |
Postbus 3208, 5003 DE Tilburg | Vaartweg 2. 4905BL Oosterhout | 06-52366061 | 088-2250562| ***@***.******@***.***> |

Van: Oosjoost ***@***.***>
Verzonden: donderdag 17 juni 2021 16:25
Aan: OIV-NL-QGIS/QGIS_project ***@***.***>
CC: Kuijpers, Martijn ***@***.***>; Author ***@***.***>
Onderwerp: Re: [OIV-NL-QGIS/QGIS_project] Het kunnen wijzigen van object contouren lukt niet meer in de laatste versie 3.3.2 (#130)


Is dit wel zo?

-

**Comment by OIV-NL-QGIS** [comment]
Beste Martijn,
Het zou helpen om te gaan updaten naar de nieuwste versie.
Daar hebben wij allemaal geen problemen met het wijzigen van de contouren.

Groetjes Bob

**Comment by OIV-NL-QGIS** [comment]
Geen reactie van Martijn ik sluit dit draadje
