### ISSUE TITLE
Error "ValueError: Null geometry cannot be converted to a polygon"

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#131]
Momenteel lopen we tegen het probleem aan dat er in onze regio 1 pand is ingetekend, waarbij de onderstaande Python error direct verschijnt zodra je de bouwlaag wilt bewerken:
![issue0](https://user-images.githubusercontent.com/73171956/114873529-a70e0c80-9dfb-11eb-81c8-49df34fcfa2a.png)
![issue1](https://user-images.githubusercontent.com/73171956/114873535-a83f3980-9dfb-11eb-856f-abcc1c51f80c.png)

Het probleem speelt dus bij het bewerken van een reeds gevulde bouwlaag. Na het bewerken van de bouwlaag komt direct dit probleem naar voren. 

In de database hebben we gecheckt dat er geen records aanwezig met een null-value in de geom-kolom. Dat is bij eerdere opschoonacties reeds opgelost.  

Mijn collega @vnogzwarta heeft het gehele object in de testomgeving 'afgepeld', steeds meer getekende objecten verwijderd, maar het probleem is pas opgelost op het moment dat de gehele bouwlaag is verwijderd...
De afbeelding van het betreffende object stuur ik per mail naar @Oostjoost. 

Versie-informatie
Plugin: laatst beschikbare 3.3.2 release 73aa6b9ff0c4216d440ee9bf753aca53986c2e25.
QGIS: 3.16.5

**Comment by Oostjoost** [comment]
Hij zal vermoedelijk toch ergens een NULL-geometry vinden. Dit kan opgelost worden door in de plugin op te nemen dat hij eerst checked op een NULL geometry alvorens hij de snapFeatures bepaalt.
