### ISSUE TITLE
Toevoegen lijnen

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#136]
Graag toevoegen
Hulp lijn ------> Zwart fijn gestippeld  #000000
lijn voor de blusleiding (vulpunt naar afname punt) ----> bruin water ---> Stippellijn bruin #654b4b 
lijn voor contouren (hoge randen, laad docks, straat profiel enz enz)  ----> donker grijs #665c54

**Comment by Paulienv78** [comment]
Kan er specifiek aangegeven worden per lijnsoort waar ze voor gebruikt moeten gaan worden en wat het doel van de lijnen is?

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/121572023-036c6180-ca24-11eb-825c-9fe176bb4d44.png)
![afbeelding](https://user-images.githubusercontent.com/23038880/121572041-07987f00-ca24-11eb-8ce6-55ba483f33a7.png)
