### ISSUE TITLE
Toevoegen aan project vlakken

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#137]
Graag toevoegen vlakken voor:

open Water   ----> vlak blauw #0095e6
Zwembad ----> vlak blauw #0072e0

**Comment by Paulienv78** [comment]
Is het vlak voor open water bedoeld om het symbool open water te kunnen vervangen?

**Comment by ghost** [comment]
Zie ook https://github.com/OIV-NL-QGIS/QGIS_project/issues/146
