### ISSUE TITLE
Toevoegen aan project pictogrammen

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#138]
toevoegen van de volgende ontbrekende pictogrammen
Symbolen beschikbaar:
- [x] Deur (blauw streepje haaks op de muur)
- [x] Schuifdeur (winkelhaak) 
- [x] Gasdetectie paneel Tb1.011
- [x] Afsluiter SVM Tb2.026
- [x] Brandweer info kast To04
- [x] Sleutel of ringpaal NEN Tbe01 **(na vragen bij Niek /Rob Vr-rr)** 
- [x] Poller NEN Tbe02
- [x] Niet toegankelijk NEN Tbe05 **(na vragen bij Niek /Rob Vr-rr)** 
- [x] Doorrijhoogte Tbehoogte (met invul veld doorrij hoogte / label) invoeren tabel bouwlaag
- [x] Windvaan NEN TbeWindvaan
- [x] Opstelplaats overige voertuigen NEN Tb1.009
- [x] Flitslicht  NEN Tn504

Toegevoegd OIV:
- [x] Deur (blauw streepje haaks op de muur) -> ingang
- [x] Schuifdeur (winkelhaak) -> ingang
- [x] Gasdetectie paneel Tb1.011 -> Veiligheid_installatie_technisch
- [x] Afsluiter SVM Tb2.026 -> Veiligheid_installatie_technisch, Veiligheid_ruimtelijk
- [x] Brandweer info kast To04 -> Veiligheid_installatie_technisch, Veiligheid_ruimtelijk
- [x] Sleutel of ringpaal NEN Tbe01 **(na vragen bij Niek /Rob Vr-rr)** --> Point-of-interest
- [x] Poller NEN Tbe02 --> Point-of-interest
- [x] Doorrijhoogte Tbehoogte (met invul veld doorrij hoogte / label) invoeren tabel bouwlaag --> Point-of-interest
- [x] Windvaan NEN TbeWindvaan --> Point-of-interest
- [x] Opstelplaats overige voertuigen NEN Tb1.009 -> opstelplaatsen
- [x] Flitslicht  NEN Tn504 -> Veiligheid_installatie_technisch

**Comment by Paulienv78** [comment]
Zijn dit pictogrammen die al in de werkgroep besproken zijn?

**Comment by rbraggaar** [comment]
Ik kreeg van @OIV-NL-QGIS (Bob) de vraag om wat symbolen aan te leveren of aan te geven welke wij gebruiken (in **bold**).

Zie daarvoor onze legenda voor een (bijna) compleet overzicht.
https://github.com/VR-RR/vrr-oiv/blob/main/docs/Pictogrammen%20op%20de%20Digitale%20Bereikbaarheidskaart%20(DBK)%20(versie%2017%20mei%202021).pdf

De iconen staan hier https://github.com/VR-RR/vrr-oiv/tree/main/qgis/icons.

- De hellingbanen en aanpijlingen worden met een dunne zwarte lijn zelf getekend, dus geen punt symbool of vooraf gedefinieerd (hellingbaan in een driehoek vanaf bovenste punt naar beneden). Er kan wel een los waarschuwingssymbool helling bij worden geplaatst. Aanpijling heeft geen pijlpunt bij ons, maar is een lijn van plek naar symbool, evt met knikken erin.
- Poller, sleutel- en ringpaal is bij ons 1 icoon. De aansturing is een keuze in de attribuutwaarden.
- Niet toegankelijk wordt mbv een label aangegeven op de bouwlaag indien nodig, maar in de praktijk niet vaak nodig.
- Lab hoog risico wordt aangeduid met oranje gevaar arcering (45 graden, 30 cm tussenruimte). Eventueel met aanvullende labels en bordjes waar van toepassing (bijv. gevaarlijke stoffen).

In Rotterdam worden verder de deuren volgens de standaarden getekend zoals die gelden in de NEN1414 en andere aanvullende normen, ook met zwarte dunne lijn.
![image](https://user-images.githubusercontent.com/16044244/121022100-546d2300-c7a2-11eb-9d69-f4f0a39cb250.png)
![image](https://user-images.githubusercontent.com/16044244/121022007-3d2e3580-c7a2-11eb-800c-5d1a3d55515f.png)
![image](https://user-images.githubusercontent.com/16044244/121022067-4f0fd880-c7a2-11eb-88b5-09a0c4e14530.png)

**Comment by Oostjoost** [comment]
Toevoegen gevarendiamant verplaatst naar aparte issue. Deze past op dit moment niet in het datamodel. Tenzij de gegevens misschien als bijvoorbeeld een json worden opgeslagen in het label veld? Laat het maar even weten.
