### ISSUE TITLE
Pictogrammen niet-terreingebonden tonen

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#140]
Hoe kunnen we het beste pictogrammen en evt. labels tonen die niet aan een terrein gebonden zijn? Denk aan bv. afsluitbare/verzinkbare palen in een binnenstad die je altijd wilt tonen, en niet binnen het incident-terrein vallen? Wat is het handigste om te gebruiken?

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by Oostjoost** [comment]
Ik denk zelf dat er een soort "point-of-interest" tabel moet komen waarbij er niet wordt gekoppeld aan repressief object, maar óf los op de kaart, óf gekoppeld aan de basisregistratie BAG/BGT waar hij bovenop staat.

Is dus iets anders dan eerder opgenomen in de volgende comment: https://github.com/OIV-NL-QGIS/QGIS_project/issues/37#issuecomment-764837352

**Comment by vnogzwarta** [comment]
Vraag van Joost welke picto's hier aan gekoppeld moeten worden, deze na afstemming doorgeven

**Comment by vnogzwarta** [comment]
> Poller
> Sleutel of ringpaal
> Paal
> Slagboom
> Hek
> Sleutelkluis
> Losse Labels
Hiervoor de symbolen gebruiken zoals deze nu al in de OIV plugin zitten, wel handig om ook bij deze symbolen een labelfunctie te hebben.

graag aanvullen als er nog symbolen ontbreken....

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
Ik heb een nieuw schema toegevoegd (info_of_interest) waarin labels, punten en lijnen tabellen zijn opgenomen. Deze staan helemaal los van het IMROI object, waardoor het IMROI model intact blijft. Ook zou je in deze tabellen aangeleverde informatie direct kunnen inlezen.

Extra toegevoegd:

- Blusleiding HD/LD afname- en vulpunt
- Waterkanon
- Rietenkap
- Asbest
- Dekkingsprobleem DMO/TMO
- Blusleiding (lijn)
Dit waren type punten uit de tabel pictogrammen_zonder_object. Deze ga ik dan ook overzetten naar de nieuwe tabellen.

**Comment by Oostjoost** [comment]
Onder de knoppen "Bouwlaag" en "Object" komt een nieuwe knop waarbij je direct in een losse pictogrammen teken widget terecht komt.

**Comment by Joachim-Tempelaars** [comment]
Niet toevoegen:
Blusleiding HD/LD afname- en vulpunt
Waterkanon
Blusleiding
Dekkingsprobleem DMO/TMO
 
Wel toevoegen:
Slagboom

**Comment by Joachim-Tempelaars** [comment]
CADO en toetreding spoor ook toevoegen aan POI
