### ISSUE TITLE
Soft-deleting

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#143]
Is het mogelijk voor een nieuwe versie soft-deletes te integreren? Middels bv. een timestamp einde_geldigheid o.i.d.?
Dit ivm een aantal problemen die we eerder hebben ervaren met verwijderde bouwdeelscheidingen, etc. Als we hiervoor simpelweg een timestamp-veld op null hoeven te zetten om weer actief te hebben zou dat voor ons praktisch zijn. Ook al even kort besproken in het wekelijkse Teams-moment met de collega's uit het land.

**Comment by Oostjoost** [comment]
Dat is zeker mogelijk

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
@vr-cb gaat dit om alles wat mogelijk weggegooid wordt binnen OIV? Of alleen specifieke objecten?

**Comment by ghost** [comment]
Wat mij betreft alle getekende objecten, symbolen, lijnen, terrein e.d.

**Comment by Oostjoost** [comment]
Dit vraag ik omdat het verwijderen van bijvoorbeeld een bouwlaag, door de relationele inrichting, cascade veel andere symbolen, lijnen en pictogrammen in andere tabellen ook weggooit. Moet even bedenken hoe ik dit dan ga afvangen, zodat het een soft-delete wordt.

**Comment by ghost** [comment]
Heb je nog nadere info nodig of is dit helder?

**Comment by Oostjoost** [comment]
Voor nu denk ik dat de mooiste oplossing de volgende is:

Als er een DELETE wordt gedaan op een tabel in de database, dan vangt een stored procedure (TRIGGER) deze af . Deze werkt hetzelfde als de timestamp op datum_aangemaakt en datum_gewijzigd. In plaats van de daadwerkelijke DELETE wordt er dan een einddatum gegeven aan de record.

Hierdoor is:
- nooit iets echt weg, dus soft-deleted
- altijd duidelijk wanneer iets weg is gegooid
- door het verwijderen van de einddatum is het object weer actief
- alles weggooien kan nog steeds met TRUNCATE, bijvoorbeeld de complete brandkranen tabel vernieuwen

Dit houdt de volgende stappen in welke alleen in de database uitgevoerd hoeven te worden:
- [x] aanmaken trigger voor elke tabel, ook de info-of-interest tabellen en de bluswater tabellen
- [x] datum_deleted toevoegen aan elke tabel
- [x] bouwlaag views laten filteren op datum_deleted
- [x] object views laten filteren op datum_deleted
- [x] view_ wegfilteren van alle objecten met datum_deleted

Dit alles heeft geen invloed op het IMROI model, aangezien het slechts administratieve velden zijn in de database.
Zijn jullie het eens met deze oplossing?

**Comment by ghost** [comment]
Dag, wat ons betreft is dat een goede optie. Dank.

**Comment by Oostjoost** [comment]
Alle scripts in de database zijn gereed voor soft-deleting:
https://github.com/OIV-NL-QGIS/IMROI_database/blob/master/migratiescripts/migratie_3.3.8-3.3.9.sql

**Comment by Oostjoost** [comment]
Vergt geen aanpassingen aan OIV

**Comment by ghost** [comment]
Nog even een heropening van dit issue, dit hebben we net in de wekelijkse sessie besproken. 

Tijdens het testen zagen we dat een lege bouwlaag die verwijderd wordt _datum_deleted_ gevuld wordt met een timestamp, waarna deze niet meer zichtbaar is. Als het echter een bouwlaag betreft waaraan bv. symboliek gekoppeld is, dan is na verwijdering van de bouwlaag dit niet meer zichtbaar in QGIS. Tot zover het plan zoals we dat voor ogen hadden. 

We zien nu alleen dat in de database de bouwlaag een timestamp krijgt in kolom _datum_deleted_, maar dat de daaraan gekoppelde symboliek dit veld wel heeft maar niet gevuld wordt tenzij je dit specifieke symbool handmatig verwijdert. 
Komt dat omdat je dit in een view ergens opvangt, om te zorgen dat QGIS deze niet toont?

Probleem van deze situatie is dat we dan andere (view)applicaties los van QGIS niet op de tabellen in de database kunnen koppelen omdat dan niet te detecteren is of een symbool wel of niet verwijderd is.
Is het mogelijk om het veld _datum_deleted_ overal te vullen wanneer bv. de bouwlaag zelf is verwijderd waaraan deze is gekoppeld?

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/issues/261#issuecomment-1076481472

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/QGIS_project/issues/261#issuecomment-1076481472
duplicate
