### ISSUE TITLE
afbrand scenario

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#144]
Vlak voor grote brand compartimenten met / zonder installatie.

Bespreken hoe we dit maken

**Comment by Oostjoost** [comment]
@Joachim-Tempelaars zou je hier willen specificeren hoe het vlak eruit moet komen te zien? Graag met RGB of hex kleurcodes erbij?

**Comment by Joachim-Tempelaars** [comment]
De grote brandcompartiment mag de zelfde styling hebben als "Gevaarlijk nooit betreden" bij natuur.
Verder het tekst label heeft de tekst “Alleen betreden na overleg OVD”

**Comment by Oostjoost** [comment]
Wordt opgenomen in de tabel ruimten. Graag nog even afstemmen met #146 over de te gebruiken style.

**Comment by Joachim-Tempelaars** [comment]
Afstemming gedaan met #146  
Zelfde vlak als natuur alleen met tekst “Alleen betreden na overleg OVD”
