### ISSUE TITLE
Formaat/schaling iconen brandweeringang

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#145]
-- Issue wordt aangevuld, bespreken we momenteel --

Iconen zijn per regio in de database configureerbaar, maar in QGIS zijn formaten vervolgens geschaald. Bv. de iconen voor een brandweeringang zijn per laag niet even groot, terwijl het om dezelfde SVG gaat. Dan staat er bv ""$size * 0.75", wat dus niet de ingestelde formaten genereert.

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by Oostjoost** [comment]
de reden hiervan is geweest dat de symbolen ruimtelijk groter zijn dan binnen. Hiervoor is destijds een vast schaalfactor gekozen. Dit heeft niets met dezelfde SVG te maken. Indien een laag zijn symbol_name en size uit dezelfde type tabel haalt is dit het geval.

Mijn voorstel is om een extra kolom op te nemen in deze type tabellen waar één kolom gebruikt wordt voor de size voor het bouwlaag-symbool en de andere kolom voor de ruimtelijke symbolen.

Werkzaamheden:

- SQL script aanpassen db
- aanpassen van de bestaande stylings in het project
- geen aanpassingen nodig aan de plugin

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.
