### ISSUE TITLE
Terrein niet-begaanbaar maken (vlak)

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#146]
-- Wordt straks aangevuld --

**Comment by ghost** [comment]
Zie ook https://github.com/OIV-NL-QGIS/QGIS_project/issues/137

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by Oostjoost** [comment]
Mijn voorstel is om dit dan op te nemen in de tabel/laag Sectoren. Graag even specificeren wat de vulkleur, lijnkleur, vulstijl, lijnstijl etc... zijn. Ik denk dat dit ongeveer 30 minuten kost om deze op te nemen in OIV.

Wat mij betreft is het verstandiger om deze in 3.3.4 te stoppen, aangezien daarvoor ook 2 soorten vlakken moeten worden bijgemaakt.

**Comment by vnogzwarta** [comment]
Mag net als bij tab natuur een rode arcering worden

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
Graag nog even afstemmen met #144 over de te gebruiken style.
