### ISSUE TITLE
Totale aantal bouwlagen zien (terugzetten zoals dit in eerdere versie was)

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#147]
-- Wordt straks aangevuld --

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by Oostjoost** [comment]
Dit is een aanpassing van het datamodel, inschatting is dat dit 1 uurtje kost om het weer terug te zetten in de plugin, data-model. Vanuit LiveOp (Fryslan) is gevraagd om de minimale en maximale bouwlaag juist op te nemen in de view_ 's. Volstaat dit ook? Dan hoeft het niet ingevuld te worden maar berekent de view de maximale en minimale bouwlaag. Misschien even afstemmen met Paulien?

**Comment by vnogzwarta** [comment]
Betreft niet voor de view, wel even afstemmen of dit in het databasemodel kan blijven

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/144084323-c72c3457-a259-4655-8633-8e73545505c1.png)

**Comment by vnogzwarta** [comment]
Prima
