### ISSUE TITLE
Snap-functie in de plugin verbeteren

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#148]
-- Wordt straks aangevuld --

**Comment by vnogzwarta** [comment]
Het snappen binnen de plugin werk niet of onnauwkeurig. Als je bijv. een vlak "ruimten" aanmaakt binnen bouwkundige scheidingen wordt hierop niet gesnapt. hierdoor ontstaat een rommelig resultaat

**Comment by ghost** [comment]
Zojuist Joost gevraagd hiervoor een indicatie af te geven. Na akkoord van onze organisatie kunnen wij dit dan oppakken.

**Comment by Oostjoost** [comment]
Ik heb nog niet duidelijk wat hier wordt bedoeld. Snappen gaat op alle vlak en lijn lagen. (Bouwlagen, Ruimten, Bouwkundige veiligheidsvoorzieningen) en zelfde geldt voor repressief object.

**Comment by vnogzwarta** [comment]
Hallo Joost,
Als we bouwkundige veiligheidsvoorzieningen hebben en daartussen willen we bijvoorbeeld een ruimte aangeven dan gebeurt dit niet netjes binnen deze lijnen, op de hoeken lijkt het alsof de snapfunctie werkt maar als je dan inzoomt dan is het verre van dat.
Ook als we dit netjes willen laten aansluiten op bijvoorbeeld de bouwlaag lukt dit niet mooi.

Hoop dat het een beetje duidelijk is zo….

**Comment by vnogzwarta** [comment]
Dit is dan het resultaat wat ik bedoel…

***@***.***D76844.CF095880]

**Comment by Oostjoost** [comment]
Hoi August,
Ik denk dat je een afbeelding hebt proberen toe te voegen maar die zie ik niet. Kan het zijn dat je dan wilt snappen op een kruispunt van een "hulplijn" en een ander object? Want sec snappen naar een bouwlaag, ruimte gaat toch wel goed? Als ik dat tenminste uitvoer kan ik niet reproduceren dat hij niet netjes aansluit.

Dan weet de plugin niet of je wilt snappen op de hulplijn of op bijvoorbeeld de bouwlaag. Ik vermoed dat dit het is...... Hoe zou dit wel moeten worden afgehandeld? Mogelijkheden:
- Niet meer snappen op hulplijnen (makkelijk te realiseren)
- Binnen een bepaalde afstand van bijvoorbeeld een bouwlaag of een bouwkundige veiligheidsvoorziening niet meer snappen op een hulplijn (iets lastiger om te maken)
- Kruisingen bepalen tussen de lijnen en die als snapmogelijkheid toevoegen en de voorkeur geven boven de andere snapmogelijkheden. (moeilijk te maken)

Gr Joost

**Comment by vnogzwarta** [comment]
Goedemorgen Joost,

Als ik vanuit de plugin 2 bouwkundige scheidingen van bijv. 60 min heb getekend in een bouwlaag en ik wil daartussen de ruimte voorzien van een “groen”vlak dsan krijgen we dit gewoon niet netjes tussen deze 60 min. lijnen. ik neem aan dat je zou moeten kunnen snappen op de beginpunten van deze lijnen of als de lijn een hoek maakt van 90 graden op deze hoek kunt snappen.
Ik heb in de bijlage nog een keer een voorbeeld meegestuurd.

**Comment by Oostjoost** [comment]
Ik zie nog steeds geen bijlage. Ik denk toch echt dat je de bijlage even via de GitHub moet plaatsen.

**Comment by Oostjoost** [comment]
https://user-images.githubusercontent.com/23038880/123260615-0c663400-d4f6-11eb-8606-8700ace6451b.mp4

**Comment by Oostjoost** [comment]
Zou je mij kunnen uitleggen wat je hier aan zou willen verbeteren? Ik kan mij de punten bedenken zoals ik boven heb genoemd. De hulplijn kruist de bouwlaag-lijn, nu weet de plugin niet of hij nu moet snappen op de bouwlaag of op de hulplijn. De voorstellen hierboven kunnen mogelijk een oplossing zijn voor dat probleem.

**Comment by vnogzwarta** [comment]
Hallo Joost,
Als ik jou gestuurde filmpje bekijk dan klopt het precies, als ik het zelf probeer dan krijg ik wel het zwarte snap kruisje te zien maar als ik dan klik en vervolgens doorga naar het volgende punt etc. dan staat uiteindelijk het vlak naast de snappunten. Het lijkt wel of de lijn wel wordt gepakt als snappunt maar een hoek van een lijn niet kan dat het probleem zijn?
Hij snapt ook op de hulplijn en niet op de lijn die je eigenlijk wilt hebben.

**Comment by vnogzwarta** [comment]
![snappen](https://user-images.githubusercontent.com/66950297/123262692-78499c00-d4f8-11eb-9fb2-921d49e33512.jpg)

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.

**Comment by Oostjoost** [comment]
Ik heb de MapTool zo aangepast dat er een grotere prioriteit gegeven wordt aan het snappen op hoekpunten. Dit houdt in dat er binnen een bepaalde afstand vanaf een hoek gesnapt gaat worden op deze hoek en niet op een deel van het segment. Zie video ter verduidelijking.

https://user-images.githubusercontent.com/23038880/150031203-b8faeb91-c19b-4fad-900b-276785b44b78.mp4

Dit zou moeten verhelpen dat het snappen in de bovenstaande beschreven voorbeelden niet goed gaat. 
Jullie moeten maar even testen of dit goed is zo.
