### ISSUE TITLE
Sleutelkluis plaatsen aanduiding "geen ingang gevonden

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#152]
Het symbool sleutelkluis wordt altijd gekoppeld aan een ingang. Als hij geplaatst wordt zonder ingang dan wordt het symbool niet opgeslagen. Kan er een melding getoond worden als er geen ingang is waar de sleutelkluis aan gekoppeld wordt? Dan is dit gelijk een goede attentie voor de gebruiker

**Comment by Oostjoost** [comment]
Er is reeds een foutmelding als er niet gekoppeld kan worden doordat de "nearest neighbour" geen ingang vindt om aan te koppelen.
