### ISSUE TITLE
Gevaren diamant (met 4 label invul velden voor elk vlak 1 pull down menu)

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#154]

**Comment by OIV-NL-QGIS** [comment]
Oostjoost comment -> Toevoegen gevarendiamant verplaatst naar aparte issue. Deze past op dit moment niet in het datamodel. Tenzij de gegevens misschien als bijvoorbeeld een json worden opgeslagen in het label veld? Laat het maar even weten.

Idd toevoegen als Json

**Comment by OIV-NL-QGIS** [comment]
ingetrokken door vrzw
