### ISSUE TITLE
Lab hoog risico (na vragen bij Niek /Rob Vr-rr)

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#156]

**Comment by Joachim-Tempelaars** [comment]
Lab hoog risico wordt aangeduid met oranje gevaar arcering (45 graden, 30 cm tussenruimte). Eventueel met aanvullende labels en bordjes waar van toepassing (bijv. gevaarlijke stoffen).

**Comment by OIV-NL-QGIS** [comment]
laten we vallen
