### ISSUE TITLE
Schaling iconen/lijnen

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#158]
In de laatst beschikbare release schalen lijnen/iconen niet goed. Verschillende zoomniveau's:
![img1](https://user-images.githubusercontent.com/73171956/125605885-325a3c9a-3d03-41c9-a2ae-487b11aa0996.jpeg)
![img2](https://user-images.githubusercontent.com/73171956/125605892-200d2995-0acc-4429-aac8-6c4889435f41.jpeg)
![img3](https://user-images.githubusercontent.com/73171956/125605903-c1d4a0e1-dd8b-47dc-b91a-24a2dfc5b1ae.jpeg)
![img4](https://user-images.githubusercontent.com/73171956/125605910-36e96b25-c09f-4ffb-a3ea-846d2a65a2f9.jpeg)
![img5](https://user-images.githubusercontent.com/73171956/125605924-7610e87f-711c-42b2-ac68-1189f94a2e13.jpeg)

Testversie: 485e38e02d4d0c79068d9fdcc09f8ba132bba6e3
QGIS versie 3.16.5

**Comment by ghost** [comment]
Ik dacht dat alle icons inmiddels SVG's betroffen, maar zo te zien niet alles.

**Comment by OIV-NL-QGIS** [comment]
de style van de lijnen lokaal gaat niet automatisch mee met de geoserver DB

**Comment by ghost** [comment]
We gebruiken geen WFS maar de database-koppeling (net als de voorgaande versies)
