### ISSUE TITLE
Icoon laadpaal werkt niet

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#159]
Icoon laadpaal werkt niet (tabblad gevaren onder terrein).
![img](https://user-images.githubusercontent.com/73171956/125606160-eaaccaad-b451-42d9-82d5-f1d094975638.png)

Testversie: 485e38e02d4d0c79068d9fdcc09f8ba132bba6e3
QGIS versie 3.16.5

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/125644360-9c525bb2-ccc2-4c8c-baaf-bb3fee8b9d11.png)

**Comment by Oostjoost** [comment]
De button was nog niet gekoppeld aan het juiste type. ook heb ik hem toegevoegd aan de bouwlaag teken mogelijkheden.
