### ISSUE TITLE
import DXF -> deur pictogram aan mapping toevoegen

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#160]
Voor het invoeren van deur lijnen naar pictogram deur graag een mapping mogelijkheid maken zodat de deur lijnen omgezet worden naar deur pictogram.

**Comment by Oostjoost** [comment]
conversie van lijn naar pictogram is niet zomaar even mogelijk in een mapping van lijn naar lijn.

**Comment by Oostjoost** [comment]
Voordat we deze kunnen ontwikkelen is het noodzakelijk om eerst functioneel beter te omschrijven hoe dit dan moet gaan werken. Eén haakse lijn op een muur met het type (kolom Layer in DXF) kan nog wel worden omgezet. Maar wat als dit een branddeur is met een zigzag lijn over de haakselijn heen? Zijn dit meerdere lijnen in de DXF? Dan is het een uitdaging om deze lijn om te zetten naar een pictogram.

Mag ik er vanuit gaan dat het symbool dan altijd in dezelfde richting en op het middelpunt mag worden geplaatst?

Graag uit 3.3.8 halen aangezien dit nooit voor volgende week gerealiseerd kan worden.

**Comment by OIV-NL-QGIS** [comment]
Mag ik er vanuit gaan dat het symbool dan altijd in dezelfde richting en op het middelpunt mag worden geplaatst? ja dat klopt

**Comment by Oostjoost** [comment]
gereed om te testen
resolves #160
