### ISSUE TITLE
Node tool voor aanpassen bouwvlak in plugin in bouwen.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#161]
Doordat de NODE tool niet in de plugin zit gaan de tekenaars buiten de plugin omwerken dat is ongewenst.
Graag de Node tool bij de groep edit zetten.

**Comment by Oostjoost** [comment]
alle tekentools in de plugin zijn apart geprogrammeerd. Dit is bijna niet mogelijk om ook te programmeren, anders dan het via een knopje aanzetten van die functie.

**Comment by OIV-NL-QGIS** [comment]
is niet meer nodig
