### ISSUE TITLE
Functies van de werkbalk geavanceerd digitaliseren in de plugin groep edit toevoegen.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#162]
Doordat de werkbalk mogelijkheden niet in de OIV plugin zit gaat men buiten om de plugin werken wat ongewenst is.

**Comment by Oostjoost** [comment]
alle tekentools in de plugin zijn apart geprogrammeerd. Dit is bijna niet mogelijk om ook te programmeren, anders dan het via een knopje aanzetten van die functie.
