### ISSUE TITLE
de lijnen contouren en aanwijslijn staan nu onder tab algemeen.bereikbaarheid naar andere plek?

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [OIV-NL-QGIS/QGIS_project#163]
de lijnen contouren en aanwijslijn staan nu onder tab algemeen.bereikbaarheid dat is niet de juiste benaming denk ik.
Kunnen ze naar een naar tab algemeen.xxx  ?? plek met titel??  duiding, verduidelijken?

**Comment by Oostjoost** [comment]
Is juist in overleg daar geplaatst.

**Comment by Joachim-Tempelaars** [comment]
Wordt in september 2021 opgepakt

**Comment by OIV-NL-QGIS** [comment]
Graag onder de pictogrammen plaatsen

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/148912988-abc518ad-47f4-4661-8baa-d8061c55365f.png)
