### ISSUE TITLE
Vlakken "bijzonder terrein"onder TAB natuur

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#164]
Onder Tab natuur en dan de vlakken van “bijzonder terrein” maken eigen contouren na het tekenen van bijvoorbeeld een rechthoek:
![img](https://user-images.githubusercontent.com/73171956/125647223-201e24e3-2ece-44ac-a5fa-84c9d5d8588c.png)

Testversie: 485e38e02d4d0c79068d9fdcc09f8ba132bba6e3
QGIS versie 3.16.5

**Comment by Oostjoost** [comment]
Is geen bug..... dit zijn "hele dikke" lijnen en een heel klein vlakje. Zie, #158
