### ISSUE TITLE
Veld datum_gewijzigd: wanneer geactualiseerd?

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#170]
Wordt het veld datum_gewijzigd bijgewerkt als er bv. een nieuwe bouwlaag wordt gekoppeld (bv. bij bouwkundige veiligheidsvoorzieningen) of gebeurt dit alleen bij wijzigingen van bv. de geometrie?
Hoor 't graag, dank vast.

**Comment by Oostjoost** [comment]
Deze wordt alleen gewijzigd bij een update van de record zelf.

**Comment by ghost** [comment]
Pakken wij intern verder op.
