### ISSUE TITLE
Functies in het "EDIT"scherm van de plugin vasthouden

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#184]
Als er bijvoorbeeld gekozen wordt voor de functie "roteren"dan moet je voor elke handeling steeds deze functie selecteren. Kan dit zo worden gemaakt dat de functie wordt 'vastgehouden"?

**Comment by Oostjoost** [comment]
Dat kan zeker, net zoals bij het tekenen van de symbolen kunnen alle acties worden blijven vastgehouden. Moet dit dan ook voor alle andere acties gaan gelden of slechts enkele?

**Comment by vnogzwarta** [comment]
Denk dat het goed is om dit even in de groep te bespreken, pakken we op

**Comment by vnogzwarta** [comment]
Functies EDIT 
![image](https://user-images.githubusercontent.com/66950297/139652805-24aaa85c-32be-44ec-a5ca-0982d9e14a9a.png)

**Comment by ghost** [comment]
Het oppakken van dit issue nemen wij (VNOG) voor onze rekening. Plannen we in gezamenlijkheid in.
