### ISSUE TITLE
Check if BAG via PDOK WFS performes

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#2]

**Comment by gisnederland** [comment]
Possible alternative: link the BAG WFS (as a foreign datawrapper) in PostGIS, and turn this into a materialized view. 
But perhaps too fancy and prone to postgres-configuration varieties.

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/OIV_project/issues/2#issuecomment-635910756 Thanks for your comment!

In former versions we experienced problems with the BAG WFS, so we created a bag_extent and also a bgt-extent within the project to query these extents. These extents were created from NLEXTRACT PostGIS download.

At the moment we are shifting from a PostGIS service connection towards a WFS connection in QGis, creating more possibilities to arrange the security and making it possible for external users to edit the data.

This also gives possibilities to reconsider the using of the BAG WFS instead. We are already using the BAG API for questioning addresses. Also looking for a good way to query the BGT.

**Comment by Oostjoost** [comment]
@OIV-NL-QGIS en @Paulienv78 , hoe om te gaan met de "tunnel" en "overige bouwwerken" welke opgenomen zijn in het bag_extent van de database, maar eigenlijk vanuit de BGT komen?

**Comment by Oostjoost** [comment]
@OIV-NL-QGIS moeten we dit nog oppakken?

**Comment by Oostjoost** [comment]
In de release van 3.3.0 komt de mogelijkheid om zelf te kiezen of je gebruik maak van de BAG uit de database of dat de BAG WFS wordt gebruikt. De gebruiker kan via het plugin menu switchen tussen de verschillende registraties.
