### ISSUE TITLE
Python foutmelding bij het tekenen van twee sectoren op elkaar

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#20]
In versie 3.1.8 heb ik tijdens het tekenen van een evenement eerst een pubiekszone (sector) getekend en daarna een tent (sector) daarop getekend. Hierna kan ik wel de publiekszone selecteren maar als ik de tent selecteer krijg ik een foutmelding. Dit komt doordat er dan twee sectoren boven op elkaar staan.
Als ik de publiekssector verwijder dan kan ik daarna wel de tent verwijderen.

**Comment by Oostjoost** [comment]
Dit gold voor alle lagen waarbij meerder features op elkaar stonden of in ieder geval binnen de selectie tolerantie van de identify tool. Dit betreft een bug op een al eerder ontwikkelde functionaliteit.
