### ISSUE TITLE
Maken symbool voor scenario's

### ISSUE THREAD

**Issue by Paulienv78** [OIV-NL-QGIS/QGIS_project#211]
Binnen de VRF willen we gaan werken met de mogelijkheid van scenario's aangeven in OIV. 
Hiervoor zou het mooi zijn als er een symbool (boekje met !) beschikbaar komt in oiv die laat zien dat er scenarios beschikbaar zijn voor het betreffende object.

**Comment by Oostjoost** [comment]
Let wel:
Scenario's is tekstuele informatie en heeft dus geen x,y coördinaat.

**Comment by Paulienv78** [comment]
Is het mogelijk om een symbool te maken die gelijk schrijft naar de tabel scenario’s? Dan geef je een attentie dat er een scenario beschikbaar is voor het object… Maar kan je dan nog wel de attribuutdata tonen door op het symbool te klikken?


  1.  Is het mogelijk;
  2.  Zo ja, hoeveel tijd kost het ontwikkelen;
  3.  Is zo’n constructie überhaupt wenselijk?

**Comment by BobHulst** [comment]
De bedoeling is dat er een picto bij komt met een boekje met een i er op die een x en y mee krijgt.
Dit picto moet net als de huidige picto`s in een object meerdere keren geplaatst kunnen worden.
Voorbeeld object met meerdere hallen met per hal eigen senario.
Achter dit picto mooet dan de senario`s komen.

Dit is besproken en goed gekeurd in de github oiv werkgroep en past binnen IMROI (picto met x en y bestaan al er komt alleen een dynamische koppeling tussen senario`s en het picto) eigenlijk wordt het hetzelfde als de picto van gevaarlijke stoffen en meerdere stoffen(meerder senario`s).

**Comment by Paulienv78** [comment]
![guide](https://user-images.githubusercontent.com/64782528/150632908-75016508-c8ab-4588-bd48-46d126f5d34d.svg)
![guide](https://user-images.githubusercontent.com/64782528/150632918-ec348ba8-ea86-4159-969c-89465770d121.png)

**Comment by Paulienv78** [comment]
![information](https://user-images.githubusercontent.com/64782528/150632948-85f71546-ccc3-4b77-ba49-8b7b915298ec.png)
![information](https://user-images.githubusercontent.com/64782528/150632956-f641d742-6e0e-4c11-84f0-76d8223dfd07.svg)

deze kwam ik ook nog tegen

**Comment by Oostjoost** [comment]
Op welke wijze willen jullie er een document aan koppelen? mijn voorstel is door het toevoegen van een URL, aangezien ik niet voor een VR kan bepalen waar ze de daadwerkelijke document willen opslaan.

En klopt mijn veronderstelling dat er dus meerdere scenario's aan één symbool kunnen hangen?

**Comment by BobHulst** [comment]
Ja prima dan zou het net als de geoserver kunnen zijn met de pdf`s

Met vriendelijke groet,


Bob Hulst

**Comment by Paulienv78** [comment]
Ja, werken met een url zou mooi zijn

**Comment by Oostjoost** [comment]
En vraag 2?

**Comment by Paulienv78** [comment]
Excuus, die stond er niet bij in de mail, wel op de github zelf.

Bob had de voorbeelden met meerdere scenario’s bij een object. Ik heb die voorbeelden niet zo…
Ik kan me voorstellen dat je per BAG pand een scenario kan hebben en dat je in een heeft groot object verschillende BAG panden kunt hebben, dan zou je per pand een symbool kunnen plaatsen met het scenario wat je voor het pand gaat gebruiken. Als je dan meerdere scenario’s onder 1 symbool plaatst wordt het denk ik voor de bevelvoerder/ovd alleen maar onduidelijk.

Ik wil graag Bob zijn mening hier over horen. @bob hulst ***@***.******@***.***> hoe had jij het in je hoofd?

Groet Paulien

**Comment by Oostjoost** [comment]
Het volgende net i.o.m. Bob afgesproken:

- [x] standaard URL-pad opnemen in een instellingen tabel in het schema algemeen
- [x] standaard URL geldt altijd, daarbinnen geeft de gebruiker de bestandsnaam op
- [x] Gestandaardiseerde scenario's kunnen worden aangeklikt via een drop-down, als hij er niet tussenstaat wordt het vrije invoer
- [x] Exact hetzelfde opzetten als gevaarlijke stoffen en de opslaglocaties
- [x] Gebruiker krijgt knop om de URL te testen en dus het scenario te openen

**Comment by Paulienv78** [comment]
Mooi, eens
