### ISSUE TITLE
Toevoegen van een deur

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#32]
Vanuit DXF - bestanden komen vaak deuren ook door. Deuren weergeven als een lijn haaks op de muur.

Mogelijk de deur weergeven hetzelfde als de kruisende lijn. Dus als het een brandwerende scheiding is dan deze ook weergeven in dezelfde kleur als de scheiding of op een andere manier?

Is dit een gewenste toevoeging? Wens uit Zuid Limburg.

**Comment by OIV-NL-QGIS** [comment]
Wij hebben het hier al vaker over gehad. 
Dit is idd een wens om de deur uit te voeren als pictogram met een lijn haaks op de scheiding met wat ons betreft een blauwe kleur.

**Comment by OIV-NL-QGIS** [comment]
dubbele issue
