### ISSUE TITLE
Toevoegen van pictogrammen zonder object aan Points of Interest

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#37]
Graag feedback welke symbolen overgezet moeten worden. Zie in jullie database de tabel "pictogrammen zonder object"
- [ ] Overzetten van de ene naar de andere tabel
- [ ] Oude tabel opschonen
- [ ] Symbolen opnemen in plugin

**Comment by Oostjoost** [comment]
Nog niet duidelijk of er wel of niet altijd gekoppeld moet worden aan een repressief object. Ik wil deze even doorschuiven naar 3.4

**Comment by Oostjoost** [comment]
Eigenlijk zouden deze registratie op een ander manier moeten worden opgezet. Bijna alle zaken die worden geregistreerd als point-of-interest of als "pictogram-zonder-object" betreft een attribuut van een bestaand object.

Dus een bag-object kan een rietendak, asbest hebben, maar ook bijvoorbeeld een opvanglocatie zijn of een restaurant. Dit zou dus niet een kaartlaag moet zijn waarbij symbolen op de kaart worden gezet, maar waarbij een bag object extra informatie krijgt.

Indien dan bijvoorbeeld een bag-pand is gesloopt en niet meer terugkomt is gelijk ook je data opgeschoond. Kan bijvoorbeeld worden geregistreerd in de gebruiksfuncties. Achteraf kun je op basis van deze attributen wel een kaartlaag maken van alle rietendaken bijvoorbeeld.

@OIV-NL-QGIS, graag jullie reactie.

**Comment by vnogzwarta** [comment]
De noodzaak om een pictogram te kunnen plaatsen zonder dat deze aan een object gekoppeld is is ook aanwezig!

Je wilt een bepaalde voorziening kunnen aangeven in bijvoorbeeld een winkelgebied ( bijzondere manier van verzinkbare palen)

**Comment by ghost** [comment]
Zie ook https://github.com/OIV-NL-QGIS/QGIS_project/issues/140

**Comment by OIV-NL-QGIS** [comment]
dubbele issue zie #140
