### ISSUE TITLE
Kaartblad aanmaken voor 1:25.000 print versie en bij overig

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#42]
- [x] Aanmaken tabel kaartbladen in dimensie-database en als laag toevoegen, styling rode rand stippellijn
- [x] Tekenen van kilometergrid koppelen aan GRID evenementen
- [x] Keuze aan gebruiker 1:25.000 of overig
- [x] Bij 1:25.000 afstand grid-lijnen standaard instellen op 1000m, niet aanpasbaar
Onderstaande geldt zowel voor 1:25k als overig
- [x] Keuze voor het print formaat
- [x] Keuze portrait of landscape
- [x] Plaatsen tijdelijk kader op het canvas, kader valt altijd gelijk met kilometergrid (linksonder)
- [x] Gebruiker kan de kaart slepen naar de gewenste positie, tijdelijk kader verspringt mee.
- [x] Daarna aanmaken grid en kaartblad

**Comment by Joachim-Tempelaars** [comment]
Besproken met Joost

**Comment by Oostjoost** [comment]
Plugin is gereed, nu de printomgevingen nog maken
