### ISSUE TITLE
OIV natuur styling POI

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#53]
Uitgangspunt is printen 1:25.000 en ondergrond top 25

Volgende symbolen groter maken omdat ze niet te zien zijn bij printen en bij zoomlevel 1:25.000 (grote als POI camping, wildrooster, enz..)
Passeerplaats
Wegafsluiting
Wegafsluiting passeer baar
Overdracht plaats 
Heli landplaats
Heli verboden 
Zwaartepunt
Vuurhaard

Bivakplaats vergroten tot 2x POI camping, wildrooster, enz...
Label in centrum bivakplaats plaatsen en 120% groter

Inrijpunt vergroten tot 2x POI camping, wildrooster, enz...

**Comment by Oostjoost** [comment]
repressief object gereed
bivak en inrijpunt nog doen, dit worden dan speciaaltjes.
