### ISSUE TITLE
OIV natuur styling grid

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#54]
In linkeronderhoek van elk vak van het grid het vaknummer vermelden.

Zichtbaar zijn van zoomlaag  0 tot 1:10.000

**Comment by Oostjoost** [comment]
![afbeelding](https://user-images.githubusercontent.com/23038880/104769692-fba7da00-576f-11eb-8066-8c81f7b70443.png)
@Joachim-Tempelaars is dit echt de bedoeling? Ik vind het nou niet echt mooi.

**Comment by Joachim-Tempelaars** [comment]
Vaknummers in de vakken hoeven niet in de print terug te komen is alleen nodig bij digitale versie. Vandaar zichtbaar van 0 tot 1:10000

**Comment by Oostjoost** [comment]
Bij een print van 1:25000 komt hij ook niet terug, net gechecked
