### ISSUE TITLE
Aanpassen achtergrondkaart bij printen

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#56]
Alle lagen in de printomgeving zijn vast ingesteld en dus vergrendeld in de printomgeving.
Mijn voorstel is om alle lagen van de kaart te ontgrendelen en dat de gebruiker in lagen beheer zelf kan instellen welke lagen in de print aanstaan.

Zijn jullie het hiermee eens?

Anders moet dit geprogrammeerd worden en is het daarnaast ook niet mogelijk om lagen aan/uit te zetten in de print omgeving.

**Comment by Joachim-Tempelaars** [comment]
Is vooralsnog oké.

Zal het in volgende tests en presentaties mee nemen.
