### ISSUE TITLE
Fout melding bij opstarten project OIV 3.2.8

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#68]
![image](https://user-images.githubusercontent.com/41467018/105225330-b49a5a00-5b5e-11eb-9e6a-0fa2e5e1a48d.png)

**Comment by Oostjoost** [comment]
Is reeds opgelost. Ik had hem per ongeluk opgeslagen met de plugin config laag opstelplaats erbij. Deze laag is reeds verwijderd.
