### ISSUE TITLE
Add new functionality (3.2.0) tot the manual

### ISSUE THREAD

**Issue by Oostjoost** [OIV-NL-QGIS/QGIS_project#7]

**Comment by Oostjoost** [comment]
Alle functionaliteit voor 3.2.0 moet nog worden verwerkt in de handleiding. Zie ook releasnotes

**Comment by Oostjoost** [comment]
@OIV-NL-QGIS hoever staat het hiermee?

**Comment by OIV-NL-QGIS** [comment]
vervallen is veroudert
