### ISSUE TITLE
Kaardblad met kilometergrid

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#74]
Als men de instelling bij "kies een schaal" veranderd in "Anders" blijft de "kaartblad preview"  1000 meter verspringen

**Comment by Oostjoost** [comment]
Dit is ook de bedoeling aangezien het startpunt (links onder) zoals afgesproken ook altijd op een kruispunt van het kilometergrid ligt. Vanaf dat startpunt wordt wel de ingestelde grootte van het grid getekend
