### ISSUE TITLE
Symbool grote voor print

### ISSUE THREAD

**Issue by Joachim-Tempelaars** [OIV-NL-QGIS/QGIS_project#75]
Mogelijkheid maken om de symbool grote alleen voor het geselecteerde object groter te printen.

**Comment by Oostjoost** [comment]
Graag enige toelichting? Nu is niet duidelijk wat hier wordt bedoeld? Alle symbolen van één repressief object of per symbool? En wat zouden deze instellingen dan moeten zijn?
