### ISSUE TITLE
Error qgis.utils.reloadProjectMacros()

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#94]
Na de installatie van de nieuwe 3.3.0 release de onderstaande foutmelding:

Er trad een fout op bij het uitvoeren van de volgende code:
```qgis.utils.reloadProjectMacros()```

```
Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 556, in reloadProjectMacros
    openProjectMacro()
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 573, in openProjectMacro
    mod.openProject()
  File "", line 18, in openProject
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ghost** [comment]
_Achtergrondinfo:_
QGIS-versie: 3.10.13-A Coruña
QGIS code revisie: 311f3bbade
Gecompileerd tegen Qt: 5.11.2
Gebruikt nu Qt: 5.11.2
Gecompileerd tegen GDAL/OGR: 3.1.4
Gebruikt nu GDAL/OGR: 3.1.4
Gecompileerd tegen GEOS: 3.8.1-CAPI-1.13.3
Gebruikt nu GEOS: 3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite: 3.29.0
Uitgevoerd met SQLite: 3.29.0
PostgreSQL Client Versie: 11.5
SpatiaLite-versie: 4.3.0
QWT versie: 6.1.3
QScintilla2 Versie: 2.10.8
Gecompileerd tegen PROJ: 6.3.2
Gebruikt nu PROJ: Rel. 6.3.2, May 1st, 2020
Versie OS: Windows 10 (10.0)
Actieve plug-ins van Python: pdokservicesplugin; db_manager; MetaSearch; oiv; processing
Python-versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by Oostjoost** [comment]
https://github.com/OIV-NL-QGIS/OIV_project/commit/14ec654d720259c32c4bf0032eea37c639c0a064
resolves #94

**Comment by Oostjoost** [comment]
Voor het opslaan van de configuratie was het nodig om tijdens de installatie QGis/OIV rechten te geven op de plugin_settings.json.
Ik heb de release aangepast, i.o.m. OIV werkgroep blijft et wel dezelfde versie.

**Comment by ghost** [comment]
Vanmorgen heb ik de laatste release 3.3.0 geïnstalleerd op de test-omgeving (die vannacht is bijgewerkt), en van mijn collega krijg ik de onderstaande melding nog steeds terug. Probleem speelt direct na het opstarten.
![Fout bij opstarten 3 3 0](https://user-images.githubusercontent.com/73171956/108847320-dd8b9000-75df-11eb-9fba-93aa23db60c7.JPG)

**Comment by ghost** [comment]
Wellicht belangrijk om aan te vullen: de instellingen in QGIS zijn zodanig geconfigureerd dat macro's altijd worden uitgevoerd.

**Comment by Oostjoost** [comment]
Bij een eerste opstart, zonder dat de BAG connectie was geconfigureerd bestond de QGIS variabele nog niet waar de connectie stond opgeslagen. Indien deze variabele bij de initiële opstart niet bestaat wordt hij aangemaakt en by default ingesteld op PDOK.
Via de config kan dit direct worden aangepast indien dit gewenst is.
