### ISSUE TITLE
symbool algemeen gevaar bouwlaag ontbreekt

### ISSUE THREAD

**Issue by vnogzwarta** [OIV-NL-QGIS/QGIS_project#97]
Het symbool voor algemeen gevaar ontbreekt bij de bouwlaag, bij repressief object zit deze er wel bij.

**Comment by Joachim-Tempelaars** [comment]
Dit symbool ontbrak ook al bij eerdere versie.

**Comment by vnogzwarta** [comment]
Klopt en zou opgelost worden bij de eerstvolgende versie volgens Joost 😊

Met vriendelijke groet,

August Zwart

Medewerker ontwerp & voorbereiding
Veiligheidsregio Noord- en Oost-Gelderland
088-3106258 | a.zwart@vnog.nl<mailto:a.zwart@vnog.nl> | www.vnog.nl<http://www.vnog.nl/>
Postbus 234, 7300 AE Apeldoorn | Bezoekadres: Stokhorstweg 1, 7006 GA Doetinchem
[cid:image002.jpg@01D70A9D.E791E340]

Van: Joachim-Tempelaars <notifications@github.com>
Verzonden: woensdag 24 februari 2021 11:10
Aan: OIV-NL-QGIS/OIV_project <OIV_project@noreply.github.com>
CC: August Zwart <A.Zwart@vnog.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [OIV-NL-QGIS/OIV_project] symbool algemeen gevaar bouwlaag ontbreekt (#97)


Dit symbool ontbrak ook al bij eerdere versie.
