### ISSUE TITLE
Fout bij toevoegen symbolen in bouwlaag

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#99]
In de nieuwe release 3.3.0 is er een probleem met het toevoegen van symbolen in een bouwlaag:
![Fout bij toevoegen symbolen in bouwlaag 3 3 0](https://user-images.githubusercontent.com/73171956/108847615-33f8ce80-75e0-11eb-804d-eeabe48c02a8.JPG)
Betreft de release van vannacht die ik opnieuw heb geinstalleerd. Melding ontvangen via een collega.

_Achtergrondinfo:_
QGIS-versie: 3.10.13-A Coruña
QGIS code revisie: 311f3bbade
Gecompileerd tegen Qt: 5.11.2
Gebruikt nu Qt: 5.11.2
Gecompileerd tegen GDAL/OGR: 3.1.4
Gebruikt nu GDAL/OGR: 3.1.4
Gecompileerd tegen GEOS: 3.8.1-CAPI-1.13.3
Gebruikt nu GEOS: 3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite: 3.29.0
Uitgevoerd met SQLite: 3.29.0
PostgreSQL Client Versie: 11.5
SpatiaLite-versie: 4.3.0
QWT versie: 6.1.3
QScintilla2 Versie: 2.10.8
Gecompileerd tegen PROJ: 6.3.2
Gebruikt nu PROJ: Rel. 6.3.2, May 1st, 2020
Versie OS: Windows 10 (10.0)
Actieve plug-ins van Python: pdokservicesplugin; db_manager; MetaSearch; oiv; processing
Python-versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by Oostjoost** [comment]
Is opgelost, kan worden getest. Met het invoeren van de keuze voor de BAG vanaf PDOK of vanuit de eigen database bleef de plugin voor snaplagen nog kijken naar de oude bag laagnaam.
